apiVersion: v1
baseDomain: DOMAIN_NAME
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: 
    azure:
      osDisk:
        diskSizeGB: CONTROL_PLANE_OS_DISK
      type: CONTROL_PLANE_VM_SIZE
  replicas: CONTROL_PLANE_REPLICA
compute:
- hyperthreading: Enabled
  name: worker
  platform: 
    azure:
      type: COMPUTE_VM_SIZE
      osDisk:
        diskSizeGB: COMPUTE_OS_DISK 
      AV_ZONES
  replicas: COMPUTE_REPLICA
metadata:
  name: CLUSTER_NAME
networking:
  clusterNetwork:
  - cidr: CLUSTER_CIDR
    hostPrefix: 23
  machineNetwork:
  - cidr: VNET_CIDR
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    baseDomainResourceGroupName: RG_DOMAIN
    region: CLUSTER_LOCATION
    networkResourceGroupName: NETWORK_RG
    virtualNetwork: VNET_NAME
    controlPlaneSubnet: CONTROL_PLANE_SUBNET
    computeSubnet: COMPUTE_SUBNET
pullSecret: 'PULL_SECRET'
fips: ENABLE_FIPS
publish: PORT_PUBLISH
